In [53]:
#MEMASANG PANDAS
import pandas as pd
pd.__version__

'3.0.2'

MENGENAL OBJEK PANDAS

In [54]:
import pandas as pd

#A. Objek Series Pandas
# Membuat Series sederhana (Contoh: Stok Produk)
data = pd.Series([60, 35, 12, 48], index=['Buku', 'Pensil', 'Penghapus', 'Pulpen'])
data


Buku         60
Pensil       35
Penghapus    12
Pulpen       48
dtype: int64

In [55]:
data.values 


array([60, 35, 12, 48])

In [56]:
data.index

Index(['Buku', 'Pensil', 'Penghapus', 'Pulpen'], dtype='str')

In [57]:
data.iloc[3]

np.int64(48)

In [58]:
data[2:4]

Penghapus    12
Pulpen       48
dtype: int64

In [59]:
#B. Series sebagai Array NumPy Umum
import pandas as pd
data = pd.Series([60, 35, 12, 48], index=['Buku', 'Pensil', 'Penghapus', 'Pulpen'])
data

Buku         60
Pensil       35
Penghapus    12
Pulpen       48
dtype: int64

In [60]:
#C. SERIES SEBAGAI DICTIONARY KHUSUS
import pandas as pd

# Membuat dictionary data luas wilayah (dalam ribuan km2)
Luas_dict = {
    'Brasil': 8515,
    'Argentina': 2780,
    'Meksiko': 1964,
    'Peru': 1285,
    'Kolombia': 1141,
    'Bolivia': 1098,
}

# Mengonversi dictionary menjadi objek Series Pandas
Luas = pd.Series(Luas_dict)

# Menampilkan hasil
Luas

Brasil       8515
Argentina    2780
Meksiko      1964
Peru         1285
Kolombia     1141
Bolivia      1098
dtype: int64

In [61]:
#D. Mengakses Item
Luas['Peru']

np.int64(1285)

In [62]:
#E. Slicing
Luas['Meksiko':'Bolivia']

Meksiko     1964
Peru        1285
Kolombia    1141
Bolivia     1098
dtype: int64

In [63]:
#F. Membangun Objek Series
import numpy as np
import pandas as pd

pd.Series([9,7,5,3,1])


0    9
1    7
2    5
3    3
4    1
dtype: int64

In [64]:
pd.Series(7, index=[5, 10, 15])

5     7
10    7
15    7
dtype: int64

In [65]:
pd.Series({30:'x', 40:'y', 50:'z'})
#Seharusnya ini object tapi ada anomali malah keluar datanya string(mungkin update di versi pandas 3 keatas)
#string seharusnya begini kalo object begini nanti gitu tulisnya di analisis

30    x
40    y
50    z
dtype: str

In [66]:
pd.Series({30:'x', 40:'y', 50:'z'}, index=[30,50])

30    x
50    z
dtype: str

OBJEK DATAFRAME PANDAS

In [67]:
#A. DATAFRAME SEBAGAI ARRAY NUMPY UMUM
# Objek Dataframe Pandas
# Dataframe sbg Array Numpy Umum
import numpy as np
import pandas as pd

luas_dict = {'Brasil': 8515,
             'Argentina': 2780,
             'Meksiko': 1964,
             'Peru': 1285,
             'Kolombia': 1141,
             'Bolivia': 1098,
            }

luas = pd.Series(luas_dict)

penduduk_dict = {'Brasil': 2158,
                 'Argentina': 4512,
                 'Meksiko': 1278,
                 'Peru': 3245,
                 'Kolombia': 5100,
                 'Bolivia': 1180,
                }

penduduk = pd.Series(penduduk_dict)
penduduk

Brasil       2158
Argentina    4512
Meksiko      1278
Peru         3245
Kolombia     5100
Bolivia      1180
dtype: int64

In [68]:
Negara  = pd.DataFrame({'Luas': luas, 
                       'Penduduk': penduduk})
Negara

,Luas,Penduduk
Brasil,8515,2158
Argentina,2780,4512
Meksiko,1964,1278
Peru,1285,3245
Kolombia,1141,5100
Bolivia,1098,1180


In [69]:
Negara.index

Index(['Brasil', 'Argentina', 'Meksiko', 'Peru', 'Kolombia', 'Bolivia'], dtype='str')

In [70]:
Negara.columns

Index(['Luas', 'Penduduk'], dtype='str')

In [71]:
#B. DataFrame Sebagai Dictionary Khusus
#DataFrame sebagai Kamus Khusus

Negara['Luas']

Brasil       8515
Argentina    2780
Meksiko      1964
Peru         1285
Kolombia     1141
Bolivia      1098
Name: Luas, dtype: int64

In [72]:
#C. Membangun Objek DataFrame
#1. Dari Objek Series Tunggal

pd.DataFrame(luas, columns=['Luas'])

,Luas
Brasil,8515
Argentina,2780
Meksiko,1964
Peru,1285
Kolombia,1141
Bolivia,1098


In [73]:
#2. Dari Sebuah List Dictionary
pd.DataFrame({'luas': luas, 'penduduk': penduduk})

,luas,penduduk
Brasil,8515,2158
Argentina,2780,4512
Meksiko,1964,1278
Peru,1285,3245
Kolombia,1141,5100
Bolivia,1098,1180


In [74]:
#3. Dari array NumPy dua dimensi
pd.DataFrame(np.random.rand(4, 4),
             columns=['p', 'q', 'r', 's'],
             index=['W', 'X', 'Y', 'Z'])

,p,q,r,s
W,0.532465,0.351079,0.071828,0.080300
X,0.724562,0.741844,0.231033,0.099035
Y,0.034135,0.295491,0.172727,0.617865
Z,0.549819,0.304082,0.345581,0.336736


In [75]:
#4. dari array terstruk NumPy

A = np.zeros(3, dtype=[('a', 'i8'), ('b', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('a', '<i8'), ('b', '<f8')])

OBJEK INDEKS PANDAS

In [76]:
#A. Indeks sebagai Array yang Tidak Berubah
# Objek index pandas
ind = pd.Index(['merah', 'biru', 'hijau', 'kuning'])
ind

Index(['merah', 'biru', 'hijau', 'kuning'], dtype='str')

In [77]:
ind [2]

'hijau'

In [78]:
ind[::3]

Index(['merah', 'kuning'], dtype='str')

In [79]:
# Objek index pandas
ind = pd.Index(['merah', 'biru', 'hijau', 'kuning'])
ind

Index(['merah', 'biru', 'hijau', 'kuning'], dtype='str')

In [80]:
#ind[1] = 0
#harusnya ga pake =0 ya
ind[1]

'biru'

In [81]:
#B. Indeks sebagai Set yang Dipesan
# Indeks sebagai set yang dipesan
obj1 = pd.Index([3, 6, 9, 12])
obj2 = pd.Index([3, 5, 7, 9])

obj1 & obj2 #intersection

Index([3, 4, 1, 8], dtype='int64')

In [82]:
#intersect
irisan = obj1.intersection(obj2)
irisan

Index([3, 9], dtype='int64')

In [83]:
obj1 & obj2 #intersection
gabungan = obj1.union(obj2)
gabungan

Index([3, 5, 6, 7, 9, 12], dtype='int64')

In [84]:
obj1 | obj2 #union

Index([3, 7, 15, 13], dtype='int64')

In [85]:
obj1 ^ obj2 #symmetric difference

Index([0, 3, 14, 5], dtype='int64')

PENGINDEKSAN DAN PEMILIHAN DATA

In [86]:
#A. Pemilihan Data dalam series
'a' in data


False

In [87]:
data.keys()

Index(['Buku', 'Pensil', 'Penghapus', 'Pulpen'], dtype='str')

In [88]:
list(data.items())

[('Buku', 60), ('Pensil', 35), ('Penghapus', 12), ('Pulpen', 48)]

In [89]:
#B. Series sebagai Dictionary
data['G'] = 1.25 
data

Buku         60.00
Pensil       35.00
Penghapus    12.00
Pulpen       48.00
G             1.25
dtype: float64

In [90]:
#C. Series Array Indexing sebagai Satu Dimensi
import pandas as pd
data = pd.Series([0.10, 0.30, 0.60, 0.90, 1.10, 1.40], 
                 index = ['a', 'b', 'c', 'd', 'e', 'f'])
data['a':'d']

a    0.1
b    0.3
c    0.6
d    0.9
dtype: float64

In [91]:
data[0:2] #interger index 

a    0.1
b    0.3
dtype: float64

In [92]:
data[(data>0.45) & (data<1.1)] #menggunakan angka besaran

c    0.6
d    0.9
dtype: float64

In [93]:
data[['a','e']] #fancy indexing

a    0.1
e    1.1
dtype: float64

In [94]:
#D. PENGINDEKSAN:LOC,ILOC DAN IX
#PENGINDEKS LOC BERLAKU UNTUK STRING SAJA
#MENCARI LOKASI DATA
data.loc['a']

np.float64(0.1)

In [95]:
data.loc['a':'c']

a    0.1
b    0.3
c    0.6
dtype: float64

In [96]:
#pengindeks iloc berlaku untuk angka atau bilangan saja
data.iloc[1:3]

b    0.3
c    0.6
dtype: float64

In [97]:
#pengindeks ix berlaku untuk bilangan dan string

data.ix = pd.Series([0.10, 0.30, 0.60, 0.90, 1.10, 1.40],
                 index = ['a', 'b', 'c', 'd', 'e', 'f'])
data.ix['a']

np.float64(0.1)

In [98]:
data.ix[1:4]

b    0.3
c    0.6
d    0.9
dtype: float64

Seleksi Data Dalam DataFrame

In [99]:
# Membuat Series Luas
Luas = pd.Series({'Brasil': 8515,
                  'Argentina': 2780,
                  'Meksiko': 1964,
                  'Peru': 1285,
                  'Kolombia': 1141,
                  'Bolivia': 1098,
                 })

# Membuat Series Penduduk
penduduk = pd.Series({'Brasil': 2158,
                      'Argentina': 4512,
                      'Meksiko': 1278,
                      'Peru': 3245,
                      'Kolombia': 5100,
                      'Bolivia': 1180,
                     })

# Menggabungkan keduanya ke dalam DataFrame
data = pd.DataFrame({'Luas': Luas, 'Penduduk': penduduk})
data

,Luas,Penduduk
Brasil,8515,2158
Argentina,2780,4512
Meksiko,1964,1278
Peru,1285,3245
Kolombia,1141,5100
Bolivia,1098,1180


In [100]:
data['Penduduk']

Brasil       2158
Argentina    4512
Meksiko      1278
Peru         3245
Kolombia     5100
Bolivia      1180
Name: Penduduk, dtype: int64

In [101]:
data.Penduduk

Brasil       2158
Argentina    4512
Meksiko      1278
Peru         3245
Kolombia     5100
Bolivia      1180
Name: Penduduk, dtype: int64

In [102]:
data.Penduduk is data['Penduduk']

False

In [103]:
data.Luas is data['Luas']

False

In [104]:
#B. DataFrame sebagai Array Dua Dimensi
data.values

array([[8515, 2158],
       [2780, 4512],
       [1964, 1278],
       [1285, 3245],
       [1141, 5100],
       [1098, 1180]])

In [105]:
data.values[1]

array([2780, 4512])

In [106]:
data.T #Data di transpose

,Brasil,Argentina,Meksiko,Peru,Kolombia,Bolivia
Luas,8515,2780,1964,1285,1141,1098
Penduduk,2158,4512,1278,3245,5100,1180
