In [ ]:
#mengakses numpy
import numpy as np
angka1 = np.array([1, 2, 3, 4, 5])

print(angka1)
print(type(angka1))

In [ ]:
#mengganti nama fungsi numpy
import numpy as np
angka2 = np.array([6, 7, 8, 9, 10])

print(angka2)
print(type(angka2))
print(np.__version__)


MEMBUAT ARRAY DIMENSI

In [ ]:
#membuat array 0-dimensi

angka3 = np.array(42)
print(angka3)

In [ ]:
#membuat array 1-dimensi

presiden = np.array(["joko-chan", "prabs-kun", "fufufafa"])
print(presiden)

In [2]:
#membuat array 2-dimensi

angka4 = np.array([[5, 7],[8,4]])
print(angka4)

NameError: name 'np' is not defined

In [ ]:
#membuat array 3-dimensi
angka4 = np.array([[[5, 7],[8,4]], [[1, 2],[3, 4]]])
print(angka4)

In [ ]:
#memeriksa dimensi array
import numpy as np
arr_1 = np.array([1, 3, 9])
arr_2 = np.array([[1, 3, 9], [4, 5, 6]])
arr_3 = np.array([[[1, 3, 9], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr_1.ndim)
print(arr_2.ndim)
print(arr_3.ndim)


In [ ]:
#membuat array N-dimensi
import numpy as np
arr_4 = np.array([14, 5,1],ndim=4)
print(arr_4)
print("Dimensi Array: ", arr_4.ndim)

Membuat Array Indexing

In [ ]:
#NumPy Array Indexing

arr_1 = np.arrau([0, 2, 3, 4, 7, 5])
print(arr_1[1])
print(arr_1[2])

In [ ]:
#indeks Numpy pada Array 2-Dimensi
import numpy as np
b = np.array([[2, 5, 1], [12, 7, 9]])

print(b)
print("Dimensi ke-1 elemen ke-2", b[0,1])
print("Dimensi ke-2 elemen ke-3", b[1,2])

SyntaxError: invalid syntax (4266834090.py, line 3)

In [2]:
#indeks NumPy pada array 3-dimensi
import numpy as np
c = np.array([[[2, 4, 5],[2, 4, 5]], [[1, 3, 9],[4, 5, 6]]])
print(c)
print(c[1, 0, 2])

[[[2 4 5]
  [2 4 5]]

 [[1 3 9]
  [4 5 6]]]
9


In [ ]:
#indeks negatif
import numpy as np
d = np.array([[2, 5, 1, 4], [12, 7, 9, 4]])
print(d)
print("elemen terahir dari dimensi ke-2: ", d[1, -1])

MEMBUAT ARRAY SLICING

In [ ]:
#NumPy array slicing 1 dimensi

import numpy as np
e = np.array([1, 3, 6, 8, 2, 3])
print(e[1:4])

print(e[:5])

print(e[-3: 1])

print(e[::2])

In [ ]:
#NumPy Array Slicing 2 dimensi
import numpy as np
f = np.array([[2, 5, 1], [12, 7, 9]])
print(f)
print(f[:2, :2])

TIPE DATA PADA NumPy

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
print(a.dtype)

b = np.array(["MBG", "19 juta lapker", "wifi gratis"])
print(b.dtype)

int64
<U14


In [6]:
#Membuat array dngn tipe data yang ditentukan
import numpy as np
a = np.array([1, 3, 4], dtype='S')
print(a)
print(a.dtype)

print(' ')
b = np.array([1, 3, 4], dtype='i')
print(b)
print(b.dtype)

#dibagian ini cantumin analisisnya nanti di laprak, kenapa bsa gini

[b'1' b'3' b'4']
|S1
 
[1 3 4]
int32


In [ ]:
c = np.array(['a', 3, 4, 5, 1], dtype = 'i')
print(c)
print(c.dtype)

#ini bakal eror karna a itu ga bsa diubah jadi integer
#kecuali string yg isinya angka baru bsa diubah jdi integer

In [7]:
#mengoncersi jenis data pada tipe yg ada
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a_new = a.astype('i')
print(a)
print(a.dtype)
print(a_new)
print(a_new.dtype)

print(' ')
a_new2 = a.astype(int)
print(a_new2)
print(a_new2.dtype)

print(' ')
b = np.array([2, 4, 5,1, 0, -1, -2]) #hanya melihat 1 sebagai true dan 0 sebagia false
bool_b = b.astype(bool)
print(bool_b)
print(bool_b.astype)

[1 2 3 4 5]
int64
[1 2 3 4 5]
int32
 
[1 2 3 4 5]
int64
 
[ True  True  True  True False  True  True]
<built-in method astype of numpy.ndarray object at 0x000001B520E5A970>


PERBEDAAN COPY DAN VIEW

In [8]:
#konversi jenis data pada tipe data yg ada
import numpy as np
arrx = np.array([1, 2, 3, 4, 5])
x = arrx.copy()#membuat salinan dari arrx
arrx[0] = 12 #membuat nilai dalam array
print(x)
print(arrx)

print(' ')
arry = np.array([1, 2, 3, 4, 5])
y = arry.view()
arry[0] = 18
print(y)
print(arry)

print(' ')
print(x.base)
print(y.base)

[1 2 3 4 5]
[12  2  3  4  5]
 
[18  2  3  4  5]
[18  2  3  4  5]
 
None
[18  2  3  4  5]


As1 = kamis 30 Apr 2026 16:00
Acc = 5 May 2026 15:30